#define PIPELINE_EDITOR_YY_IDENTIFIER 1
#define PIPELINE_EDITOR_YY_VALUE 2
#define PIPELINE_EDITOR_YY_COLON 3
#define PIPELINE_EDITOR_YY_UR_MK 4
#define PIPELINE_EDITOR_YY_UBR_MK 5
#define PIPELINE_EDITOR_YY_VAR_MK 6