#define STAGE_EDITOR_YY_IDENTIFIER 1
#define STAGE_EDITOR_YY_VALUE 2
#define STAGE_EDITOR_YY_COLON 3
#define STAGE_EDITOR_YY_ERROR 4
#define STAGE_EDITOR_YY_UR_MK 5
#define STAGE_EDITOR_YY_UBR_MK 6
#define STAGE_EDITOR_YY_VAR_MK 7